basePath: /
definitions:
  fiber.createPermissionRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  fiber.createUserRequest:
    properties:
      password:
        minLength: 8
        type: string
    type: object
  fiber.issueTokenRequest:
    properties:
      description:
        type: string
      lifetime_in_seconds:
        type: integer
      permissions:
        items:
          type: string
        type: array
    required:
    - description
    type: object
  fiber.issueTokenResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
      type:
        type: string
    type: object
  fiber.permissionResponse:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  fiber.sessionOwner:
    properties:
      device_id:
        type: string
      user_id:
        type: string
    type: object
  fiber.sessionResponse:
    properties:
      active:
        type: boolean
      expires_at:
        type: string
      id:
        type: string
      owned_by:
        $ref: '#/definitions/fiber.sessionOwner'
    type: object
  fiber.userResponse:
    properties:
      id:
        type: string
      registered_at:
        type: string
    type: object
info:
  contact: {}
  description: A minimal identity provider
  title: identity
  version: 0.0.1
paths:
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: User identifier
        in: formData
        name: identifier
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Renewable
        in: formData
        name: renewable
        type: boolean
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "415":
          description: Unsupported Media Type
        "500":
          description: Internal Server Error
      summary: Initiate a new session with local credentials
      tags:
      - Session
  /logout:
    delete:
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Revoke the current session
      tags:
      - Session
  /permission:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.permissionResponse'
        "500":
          description: Internal Server Error
      summary: Get all permissions
      tags:
      - Permission
    post:
      consumes:
      - application/json
      parameters:
      - description: Create command
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/fiber.createPermissionRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Create a new permission
      tags:
      - Permission
  /permission/{name}:
    delete:
      consumes:
      - text/plain
      parameters:
      - description: Name of the permission
        in: path
        name: name
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a permission
      tags:
      - Permission
  /session:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/fiber.sessionResponse'
            type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: List all active sessions belonging to the owner of the current session
      tags:
      - Session
  /session/{id}:
    get:
      parameters:
      - description: Session Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.sessionResponse'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get details of a session
      tags:
      - Session
  /session/active:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.sessionResponse'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get details of the active session
      tags:
      - Session
  /session/revoke/{id}:
    delete:
      parameters:
      - description: Id of the session
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Revoke a session
      tags:
      - Session
  /token:
    post:
      consumes:
      - application/json
      parameters:
      - description: Information of the token to issue
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/fiber.issueTokenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/fiber.issueTokenResponse'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Issue a new token
      tags:
      - Token
  /user:
    post:
      consumes:
      - application/json
      parameters:
      - description: Information of the user to create
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/fiber.createUserRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Create a new user
      tags:
      - User
  /user/{id}:
    delete:
      parameters:
      - description: Id of the user
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a user
      tags:
      - User
    get:
      parameters:
      - description: Id of the user
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.userResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get information about a user
      tags:
      - User
  /user/{id}/grant/{permission}:
    post:
      consumes:
      - text/plain
      parameters:
      - description: Id of the user
        in: path
        name: id
        required: true
        type: string
      - description: Name of the permission
        in: path
        name: permission
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Grant a permission to a user
      tags:
      - User
  /user/{id}/has/{permission}:
    get:
      consumes:
      - text/plain
      parameters:
      - description: Id of the user
        in: path
        name: id
        required: true
        type: string
      - description: Name of the permission
        in: path
        name: permission
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Verify if a user has a permission
      tags:
      - User
  /user/{id}/revoke/{permission}:
    delete:
      consumes:
      - text/plain
      parameters:
      - description: Id of the user
        in: path
        name: id
        required: true
        type: string
      - description: Name of the permission
        in: path
        name: permission
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Revoke a permission from a user
      tags:
      - User
  /user/me:
    delete:
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Delete the current user
      tags:
      - User
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.userResponse'
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get information about the current user
      tags:
      - User
swagger: "2.0"
