basePath: /
definitions:
  fiber.createPermissionRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  fiber.permissionResponse:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  fiber.sessionOwner:
    properties:
      device_id:
        type: string
      user_id:
        type: string
    type: object
  fiber.sessionResponse:
    properties:
      expires_at:
        type: string
      id:
        type: string
      owned_by:
        $ref: '#/definitions/fiber.sessionOwner'
    type: object
info:
  contact: {}
  description: A minimal identity provider
  title: identity
  version: 0.0.1
paths:
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: User identifier
        in: formData
        name: identifier
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Renewable
        in: formData
        name: renewable
        type: boolean
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Initiate a new session with local credentials
      tags:
      - Session
  /logout:
    delete:
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
      summary: Revoke the current session
      tags:
      - Session
  /permission:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.permissionResponse'
        "401":
          description: Unauthorized
      summary: Get all permissions
      tags:
      - Permission
    post:
      consumes:
      - application/json
      parameters:
      - description: Create command
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/fiber.createPermissionRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Create a new permission
      tags:
      - Permission
  /permission/{name}:
    delete:
      consumes:
      - text/plain
      parameters:
      - description: Name of the permission
        in: path
        name: name
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Delete a permission
      tags:
      - Permission
  /session:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/fiber.sessionResponse'
            type: array
        "401":
          description: Unauthorized
      summary: List all active sessions belonging to the owner of the current session
      tags:
      - Session
  /session/{id}:
    get:
      parameters:
      - description: Session Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.sessionResponse'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Get details of a session
      tags:
      - Session
  /session/active:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.sessionResponse'
        "401":
          description: Unauthorized
      summary: Get details of the active session
      tags:
      - Session
  /session/revoke/{id}:
    delete:
      parameters:
      - description: Id of the session
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: Revoke a session
      tags:
      - Session
  /user/{id}/grant/{permission}:
    post:
      consumes:
      - text/plain
      parameters:
      - description: ID of the user
        in: path
        name: id
        required: true
        type: string
      - description: Name of the permission
        in: path
        name: permission
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: Grant a permission to a user
      tags:
      - User
swagger: "2.0"
