// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-playground/validator/v10"
	"github.com/oechsler-it/identity/fiber"
	"github.com/oechsler-it/identity/gorm"
	"github.com/oechsler-it/identity/modules"
	"github.com/oechsler-it/identity/modules/permission"
	app3 "github.com/oechsler-it/identity/modules/permission/app"
	fiber4 "github.com/oechsler-it/identity/modules/permission/infra/fiber"
	model3 "github.com/oechsler-it/identity/modules/permission/infra/model"
	"github.com/oechsler-it/identity/modules/session"
	app2 "github.com/oechsler-it/identity/modules/session/app"
	fiber2 "github.com/oechsler-it/identity/modules/session/infra/fiber"
	model2 "github.com/oechsler-it/identity/modules/session/infra/model"
	"github.com/oechsler-it/identity/modules/user"
	"github.com/oechsler-it/identity/modules/user/app"
	fiber3 "github.com/oechsler-it/identity/modules/user/infra/fiber"
	"github.com/oechsler-it/identity/modules/user/infra/hook"
	"github.com/oechsler-it/identity/modules/user/infra/model"
	"github.com/oechsler-it/identity/modules/user/infra/service"
	"github.com/oechsler-it/identity/runtime"
	"github.com/oechsler-it/identity/swagger"
)

// Injectors from wire.go:

func New() *App {
	hooks := runtime.NewHooks()
	env := runtime.NewEnv()
	logger := runtime.NewLogger(env)
	runtimeRuntime := runtime.NewRuntime(hooks, logger)
	fiberApp := fiber.NewFiber(env, logger)
	quicFiber := fiber.NewQUICFiber(fiberApp)
	options := &fiber.Options{
		Env:     env,
		Hooks:   hooks,
		Logger:  logger,
		App:     fiberApp,
		QuicApp: quicFiber,
	}
	swaggerOptions := &swagger.Options{
		App: fiberApp,
	}
	gormOptions := &gorm.Options{
		Hooks:  hooks,
		Env:    env,
		Logger: logger,
	}
	db := gorm.NewPostgres(gormOptions)
	gormUserRepo := model.NewGormUserRepo(db, logger, hooks)
	verifyNoUserExistsHandler := app.NewVerifyNoUserExistsHandler(gormUserRepo)
	validate := validator.New()
	argon2idPasswordService := service.NewArgon2idPasswordService()
	createHandler := app.NewCreateHandler(validate, argon2idPasswordService, gormUserRepo)
	createRootUser := &hook.CreateRootUser{
		Hooks:              hooks,
		Logger:             logger,
		Env:                env,
		Repo:               gormUserRepo,
		VerifyNoUserExists: verifyNoUserExistsHandler,
		Create:             createHandler,
	}
	gormSessionRepo := model2.NewGormSessionRepo(db, logger, hooks)
	verifyActiveHandler := app2.NewVerifyActiveHandler(gormSessionRepo)
	protectMiddleware := &fiber2.ProtectMiddleware{
		VerifyActive: verifyActiveHandler,
	}
	gormPermissionRepo := model3.NewGormPermissionRepo(db, logger, hooks)
	findByNameHandler := app3.NewFindByNameHandler(gormPermissionRepo)
	grantPermissionHandler := app.NewGrantPermissionHandler(findByNameHandler, validate, gormUserRepo)
	fiberGrantPermissionHandler := &fiber3.GrantPermissionHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		Grant:             grantPermissionHandler,
	}
	revokePermissionHandler := app.NewRevokePermissionHandler(validate, gormUserRepo)
	fiberRevokePermissionHandler := &fiber3.RevokePermissionHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		Revoke:            revokePermissionHandler,
	}
	userOptions := &user.Options{
		CreateRootUser:   createRootUser,
		GrantPermission:  fiberGrantPermissionHandler,
		RevokePermission: fiberRevokePermissionHandler,
	}
	deviceIdMiddleware := &fiber2.DeviceIdMiddleware{
		App:    fiberApp,
		Logger: logger,
	}
	sessionIdMiddleware := &fiber2.SessionIdMiddleware{
		App: fiberApp,
	}
	initiateHandler := app2.NewInitiateHandler(validate, gormSessionRepo)
	findByIdentifierHandler := app.NewFindByIdentifierHandler(gormUserRepo)
	verifyPasswordHandler := app.NewVerifyPasswordHandler(argon2idPasswordService, gormUserRepo)
	loginHandler := &fiber2.LoginHandler{
		App:                  fiberApp,
		Logger:               logger,
		Env:                  env,
		Model:                gormSessionRepo,
		Initiate:             initiateHandler,
		FindUserByIdentifier: findByIdentifierHandler,
		VerifyPassword:       verifyPasswordHandler,
	}
	findByIdHandler := app2.NewFindByIdHandler(gormSessionRepo)
	revokeHandler := app2.NewRevokeHandler(validate, gormSessionRepo)
	logoutHandler := &fiber2.LogoutHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		FindById:          findByIdHandler,
		Revoke:            revokeHandler,
	}
	revokeSessionHandler := &fiber2.RevokeSessionHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		FindById:          findByIdHandler,
		Revoke:            revokeHandler,
	}
	renewHandler := app2.NewRenewHandler(validate, gormSessionRepo)
	renewMiddleware := &fiber2.RenewMiddleware{
		Logger: logger,
		Env:    env,
		Renew:  renewHandler,
	}
	findByOwnerUserIdHandler := app2.NewFindByOwnerUserIdHandler(gormSessionRepo)
	activeSessionsHandler := &fiber2.ActiveSessionsHandler{
		App:               fiberApp,
		RenewMiddleware:   renewMiddleware,
		ProtectMiddleware: protectMiddleware,
		FindById:          findByIdHandler,
		FindByOwnerUserId: findByOwnerUserIdHandler,
	}
	activeSessionHandler := &fiber2.ActiveSessionHandler{
		App:               fiberApp,
		RenewMiddleware:   renewMiddleware,
		ProtectMiddleware: protectMiddleware,
		FindById:          findByIdHandler,
	}
	sessionByIdHandler := &fiber2.SessionByIdHandler{
		App:               fiberApp,
		RenewMiddleware:   renewMiddleware,
		ProtectMiddleware: protectMiddleware,
		FindById:          findByIdHandler,
	}
	sessionOptions := &session.Options{
		DeviceIdMiddleware:    deviceIdMiddleware,
		SessionIdMiddleware:   sessionIdMiddleware,
		LoginHandler:          loginHandler,
		LogoutHandler:         logoutHandler,
		RevokeSessionHandler:  revokeSessionHandler,
		ActiveSessionsHandler: activeSessionsHandler,
		ActiveSessionHandler:  activeSessionHandler,
		SessionByIdHandler:    sessionByIdHandler,
	}
	appCreateHandler := app3.NewCreateHandler(validate, gormPermissionRepo)
	fiberCreateHandler := &fiber4.CreateHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		Create:            appCreateHandler,
	}
	deleteHandler := app3.NewDeleteHandler(gormPermissionRepo)
	fiberDeleteHandler := &fiber4.DeleteHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		Delete:            deleteHandler,
	}
	findAllHandler := app3.NewFindAllHandler(gormPermissionRepo)
	permissionsHandler := &fiber4.PermissionsHandler{
		App:               fiberApp,
		ProtectMiddleware: protectMiddleware,
		FindAll:           findAllHandler,
	}
	permissionOptions := &permission.Options{
		CreateHandler:      fiberCreateHandler,
		DeleteHandler:      fiberDeleteHandler,
		PermissionsHandler: permissionsHandler,
	}
	modulesOptions := &modules.Options{
		App:        fiberApp,
		User:       userOptions,
		Session:    sessionOptions,
		Permission: permissionOptions,
	}
	appOptions := &Options{
		Runtime: runtimeRuntime,
		Logger:  logger,
		Fiber:   options,
		Swagger: swaggerOptions,
		Modules: modulesOptions,
	}
	appApp := newApp(appOptions)
	return appApp
}
