// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/go-playground/validator/v10"
	"github.com/oechsler-it/identity/fiber"
	"github.com/oechsler-it/identity/modules"
	"github.com/oechsler-it/identity/modules/session"
	app2 "github.com/oechsler-it/identity/modules/session/app"
	fiber2 "github.com/oechsler-it/identity/modules/session/infra/fiber"
	model2 "github.com/oechsler-it/identity/modules/session/infra/model"
	"github.com/oechsler-it/identity/modules/user"
	"github.com/oechsler-it/identity/modules/user/app"
	"github.com/oechsler-it/identity/modules/user/infra/hook"
	"github.com/oechsler-it/identity/modules/user/infra/model"
	"github.com/oechsler-it/identity/modules/user/infra/service"
	"github.com/oechsler-it/identity/runtime"
)

// Injectors from wire.go:

func New() *App {
	hooks := runtime.NewHooks()
	env := runtime.NewEnv()
	logger := runtime.NewLogger(env)
	runtimeRuntime := runtime.NewRuntime(hooks, logger)
	fiberApp := fiber.NewFiber()
	options := &fiber.Options{
		Hooks:  hooks,
		Logger: logger,
		App:    fiberApp,
	}
	inMemoryUserRepo := model.NewInMemoryUserRepo()
	validate := validator.New()
	argon2idPasswordService := service.NewArgon2idPasswordService()
	createHandler := app.NewCreateHandler(validate, argon2idPasswordService, inMemoryUserRepo)
	createRootUser := &hook.CreateRootUser{
		Hooks:  hooks,
		Logger: logger,
		Env:    env,
		Model:  inMemoryUserRepo,
		Create: createHandler,
	}
	userOptions := &user.Options{
		CreateRootUser: createRootUser,
	}
	deviceIdMiddleware := &fiber2.DeviceIdMiddleware{
		App:    fiberApp,
		Logger: logger,
	}
	sessionIdMiddleware := &fiber2.SessionIdMiddleware{
		App: fiberApp,
	}
	inMemorySessionRepo := model2.NewInMemorySessionRepo()
	initiateHandler := app2.NewInitiateHandler(validate, inMemorySessionRepo)
	findByIdentifierHandler := app.NewFindByIdentifierHandler(inMemoryUserRepo)
	verifyPasswordHandler := app.NewVerifyPasswordHandler(argon2idPasswordService, inMemoryUserRepo)
	loginHandler := &fiber2.LoginHandler{
		App:                  fiberApp,
		Logger:               logger,
		Env:                  env,
		Model:                inMemorySessionRepo,
		Initiate:             initiateHandler,
		FindUserByIdentifier: findByIdentifierHandler,
		VerifyPassword:       verifyPasswordHandler,
	}
	verifyActiveHandler := app2.NewVerifyActiveHandler(inMemorySessionRepo)
	protectMiddleware := &fiber2.ProtectMiddleware{
		VerifyActive: verifyActiveHandler,
	}
	revokeHandler := app2.NewRevokeHandler(validate, inMemorySessionRepo)
	logoutHandler := &fiber2.LogoutHandler{
		App:               fiberApp,
		Logger:            logger,
		ProtectMiddleware: protectMiddleware,
		Revoke:            revokeHandler,
	}
	renewHandler := app2.NewRenewHandler(validate, inMemorySessionRepo)
	renewMiddleware := &fiber2.RenewMiddleware{
		Logger: logger,
		Env:    env,
		Renew:  renewHandler,
	}
	findByIdHandler := app2.NewFindByIdHandler(inMemorySessionRepo)
	sessionHandler := &fiber2.SessionHandler{
		App:               fiberApp,
		RenewMiddleware:   renewMiddleware,
		ProtectMiddleware: protectMiddleware,
		FindById:          findByIdHandler,
	}
	sessionOptions := &session.Options{
		DeviceIdMiddleware:  deviceIdMiddleware,
		SessionIdMiddleware: sessionIdMiddleware,
		LoginHandler:        loginHandler,
		LogoutHandler:       logoutHandler,
		SessionHandler:      sessionHandler,
	}
	modulesOptions := &modules.Options{
		App:     fiberApp,
		User:    userOptions,
		Session: sessionOptions,
	}
	appOptions := &Options{
		Runtime: runtimeRuntime,
		Logger:  logger,
		Fiber:   options,
		Modules: modulesOptions,
	}
	appApp := newApp(appOptions)
	return appApp
}
